This tutorial was originally colaborated by [Justin Johnson](https://web.eecs.umich.edu/~justincj/), [Volodymyr Kuleshov](http://web.stanford.edu/~kuleshov/) and [Isaac Caswell](https://symsys.stanford.edu/viewing/symsysaffiliate/21335). The parts of the tutorial covering PyTorch is taken from [Jovian](https://jovian.com/learn/deep-learning-with-pytorch-zero-to-gans).

This version has been adapted for Colab by [Trishna Saikia](https://trishnasaikia.github.io/), for CS 419/61 (Computer Vision), under the supervision of [Dr. Puneet Gupta](https://www.iiti.ac.in/people/~puneet/).



## Motivation

Python is a high-level, interpreted programming language on its own, but with the help of a few popular libraries (numpy, scipy, matplotlib, pandas) it becomes a powerful environment for scientific computing.

Further Python has deep learning libraries such as PyTorch and Tensorflow that has strong interoperability with other libraries, provide efficient support for GPU computing.

Finally, Python has one of the best supporting communities and sub-communities of developers, researchers and contributors.

We expect that many of you will have some experience with Python and numpy; for the rest of you, this section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing.

In this tutorial, we will cover:

* Notebooks and Google Colab
* Basic Python: Basic data types (Containers, Lists, Dictionaries, Sets, Tuples), Functions, Classes
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting
* Matplotlib: Plotting, Subplots, Images
* Pandas: A brief introduction
* Python Libraries for Image-Processing
* PyTorch and more ...

**What is a Jupyter notebook ?**

* A Jupyter notebook lets you write and execute Python code locally in your web browser.
* Jupyter notebooks make it very easy to tinker with code and execute it in bits and pieces; for this reason they are widely used in scientific computing.

**What is a Google Colab ?**
* Colaboratory, or "Colab" for short, is Google’s flavor of Jupyter notebooks that is particularly suited for machine learning and data analysis and that runs entirely in the cloud.
* Colab is free to use, requires no setup, comes preinstalled with many packages, and benefits from free access to hardware accelerators like GPUs and TPUs (with some caveats).

## A Brief Note on Python Versions

As of Janurary 1, 2020, Python has [officially dropped support](https://www.python.org/doc/sunset-python-2/) for `python2`. We'll be using Python 3.10.12 for this iteration of the course. You can check your Python version at the command line by running `python --version`.

In [ ]:
!python --version

Python 3.10.12


##Basics of Python

Python is an interpreted, high-level, general-purpose programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable.

###Basic data types

####Numbers

Integers and floats work as you would expect from other languages:

In [ ]:
x = 3
print(x)        # Printing the value of the variable
print(type(x))  # Printing the data type of the variable

3
<class 'int'>


In [ ]:
print(x + 1)   # Addition
print(x - 1)   # Subtraction
print(x * 2)   # Multiplication
print(x / 2)   # Divison
print(x // 2)  # Floor Divison
print(x ** 2)  # Exponentiation

4
2
6
1.5
1
9


In [ ]:
# Shorthand operators
x += 1     # x = x + 1
print(x)
x *= 2     # x = x * 2
print(x)

9
18


In [ ]:
y = 2.5
print(type(y))
print(y, y + 1, y * 2, y ** 2)

<class 'float'>
2.5 3.5 5.0 6.25


Note that unlike many languages, Python does not have unary increment (`x++`) or decrement (`x--`) operators.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#numeric-types-int-float-long-complex).

In [ ]:
large_integer = 1234567890123456789012345678901234567890
print(large_integer)

1234567890123456789012345678901234567890


In [ ]:
complex_number1 = complex(3.0, 4.0)  # 3.0 + 4.0j
complex_number2 = complex(5.0, 6.0)  # 5.0 + 6.0j
complex_number3 = complex_number1 + complex_number2

In [ ]:
print(complex_number3)

(8+10j)


####Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [ ]:
t, f = True, False
print(type(t))

<class 'bool'>


Now we let's look at the operations:

In [ ]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;

False
True
False


####Strings

In [ ]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter
print(hello)      # Printing the value of the string
print(len(hello)) # Printing the length of the string

hello
5


In [ ]:
hw = hello + " " + world  # String concatenation
print(hw)

hello world


In [ ]:
hw12 = '{} {} {}'.format(hello, world, 12)  # string formatting
print(hw12)

hello world 12


**String formatting** refers to the process of creating a string representation that includes placeholders, which are later filled with actual values. This allows you to construct strings dynamically by inserting variable values, expressions, or other strings into specific locations within a template string.

In [ ]:
name = "Ram"
age = 30
formatted_string = "My name is {} and I am {} years old.".format(name, age)
print(formatted_string)

My name is Ram and I am 30 years old.


String objects have a bunch of useful methods; for example:

In [ ]:
s = "hello"
print(s.capitalize())  # Capitalize a string
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another
print('  world ')
print('  world '.strip())  # Strip leading and trailing whitespace

Hello
HELLO
he(ell)(ell)o
  world 
world


You can find a list of all string methods in the [documentation](https://docs.python.org/3.7/library/stdtypes.html#string-methods).

###Containers

Containers are any object that holds an arbitrary number of other objects. Python includes several built-in container types: lists, dictionaries, sets, and tuples.

####Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [ ]:
xs = [3, 1, 7]   # Create a list
print(xs, xs[2])
print(xs[-2])     # Negative indices count from the end of the list; prints "7"

[3, 1, 7] 7
1


In [ ]:
xs[2] = 'foo'    # Lists can contain elements of different types
print(xs)

[3, 1, 'foo']


In [ ]:
xs.append('bar') # Add a new element to the end of the list
print(xs)

[3, 1, 'foo', 'bar']


In [ ]:
x = xs.pop()     # Remove and return the last element of the list
print(x, xs)

bar [3, 1, 'foo']


As usual, you can find all the gory details about lists in the [documentation](https://docs.python.org/3.7/tutorial/datastructures.html#more-on-lists).

####Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [ ]:
nums = list(range(5))
print(nums)

[0, 1, 2, 3, 4]


In [ ]:
nums = list(range(5))    # range is a built-in function that creates a list of integers
print(nums)         # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9]  # Assign a new sublist to a slice
print(nums)         # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


Can we have a 2d list in python?

####Loops

You can loop over the elements of a list like this:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

#1: cat
#2: dog
#3: monkey


####List comprehensions:

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:




In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)

[0, 4, 16]


####Dictionaries

A dictionary stores (key, value) pairs. You can use it like this:

In [ ]:
d = {'cat': 'clawy', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "clawy"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

clawy
True


In [ ]:
print('fish' in d) # Prints False as 'fish' is not a key in dict 'd'

False


In [ ]:
d['fish'] = 'glob_glob'    # Set an entry in a dictionary
print(d['fish'])      # Prints "glob_glob"

glob_glob


In [ ]:
print(d)

{'cat': 'clawy', 'dog': 'furry', 'fish': 'glob_glob'}


In [ ]:
print(d['monkey'])  # KeyError: 'monkey' not a key of d

KeyError: 'monkey'

In [ ]:
del d['fish']        # Remove an element from a dictionary
print(d)

{'cat': 'clawy', 'dog': 'furry'}


In [ ]:
print(d['fish'])  # KeyError: 'fish' not a key of d

You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/2/library/stdtypes.html#dict).

It is easy to iterate over the keys in a dictionary:

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A {} has {} legs'.format(animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [ ]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


####Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [ ]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"

True
False


In [ ]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))
animals.remove('cat')    # Remove an element from a set
print(len(animals))

2
1


_Loops_: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [ ]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#{}: {}'.format(idx + 1, animal))

#1: fish
#2: dog
#3: cat


Set comprehensions: Like lists and dictionaries, we can easily construct sets using set comprehensions:

####Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot. Here is a trivial example:

In [ ]:
d = {(x, x + 1): x for x in range(3)}  # Create a dictionary with tuple keys
print(d)
print(type(d))
t = (2, 3)       # Create a tuple
print(type(t))
print(d[t])
print(d[(1, 2)])

{(0, 1): 0, (1, 2): 1, (2, 3): 2}
<class 'dict'>
<class 'tuple'>
2
1


###Functions

Python functions are defined using the `def` keyword. For example:

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'
# ----------------------- #
for x in [-1, 0, 1]:
    print(sign())

TypeError: sign() missing 1 required positional argument: 'x'

We will often define functions to take optional keyword arguments, like this:

In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name))
# ----------------------- #
hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


##Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the `numpy` package:

In [ ]:
import numpy as np

###Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [ ]:
x = [[1,2,3],[4,5,6]]
print(x[0], x[1])
print(x)
print(type(x))

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # Create a 2x3 dimension array
print(b)
print(b.shape)
print(type(b))

Numpy also provides many functions to create arrays:

In [ ]:
a = np.zeros((2,3))  # Create an array of all zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

In [ ]:
c = np.full((3,2), 7) # Create a constant array
print(c)

In [ ]:
d = np.eye(4)        # Create a 2x2 identity matrix
print(d)

In [ ]:
e = np.random.random((2,2)) # Create an array filled with random values
print(e)

[[0.06670729 0.1317195 ]
 [0.02382144 0.54633755]]


###Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [ ]:
import numpy as np

# Create the following array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]

b = a[0:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [ ]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])
print(b[0, 0])

2
77
77


In [ ]:
# a ---> b deep copy --> provides new address; shallow copy gives vars with same address

In [ ]:
# np.copy() https://numpy.org/doc/stable/reference/generated/numpy.copy.html

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
b = a # Shallow copying
c = np.copy(a) # Deep copying

print(a)
print("==========")

b[0][0] = 10
print(a)
print(b)
print("==========")

c[0][0] = 20
print(a)
print(c)

###Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

###Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[.1,2],[.3,4]])
print((x))
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[0.1 2. ]
 [0.3 4. ]]
[[ 5.1  8. ]
 [ 7.3 12. ]]
[[ 5.1  8. ]
 [ 7.3 12. ]]


In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Note that `*` is elementwise multiplication, not matrix multiplication. We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [ ]:
v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


[9, 10] • [11, 12] = 9 * 11 + 10 * 12 = 219

You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [ ]:
print(v @ w)

219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
x = np.array([[1,2],[3,4]])
v = np.array([9, 10])

print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [ ]:
x = np.array([[1, 2, 4],[3, 4, 5]])
y = np.array([[2, 7, 8, 9], [1, 2, 3, 4], [8, 11, 1, 7]])

print(x.shape)
print(y.shape)

print(x.dot(y))
print(np.dot(x, y))
print(x @ y)
print((x @ y).shape)

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(x)
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


###Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version while using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([[1, 0, 1], [1, 2, 9]])
y = x + v  # Add v to each row of x using broadcasting
print(y)

ValueError: operands could not be broadcast together with shapes (4,3) (2,3) 

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(v)
print(w)

print(np.reshape(v, (3, 1)) * w)

# print(v * w) # Throws an error.
# ValueError: operands could not be broadcast together with shapes (3,) (2,)

[Difference between numpy.array shape (R, 1) and (R,)](https://stackoverflow.com/a/22074424/6521550)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3],
              [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

In [ ]:
# Add a vector to each column of a matrix

# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.

##Matplotlib

Matplotlib is a plotting library. In this section give a brief introduction to the `matplotlib.pyplot` module, which provides a plotting system similar to that of MATLAB.

In [ ]:
import matplotlib.pyplot as plt

By running this special iPython command, we will be displaying plots inline:

In [ ]:
%matplotlib inline
# Assignment 1 : What is inline display?

The statement `%matplotlib inline` indicates to Jupyter that we want to plot the graphs within the notebook. Without this line, Jupyter will show the image in a popup. Statements starting with `%` are called magic commands and are used to configure the behavior of Jupyter itself. You can find a full list of magic commands here: https://ipython.readthedocs.io/en/stable/interactive/magics.html .

###Plotting

The most important function in `matplotlib` is plot, which allows you to plot 2D data. Here is a simple example:

In [ ]:
np.arange(0,1,0.1)

In [ ]:
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x, y)

With just a little bit of extra work we can easily plot multiple lines at once, and add a title, legend, and axis labels:

In [ ]:
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
# plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])

###Subplots

You can plot different things in the same figure using the subplot function. Here is an example:

In [ ]:
# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)

plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

You can read much more about the `subplot` function in the [documentation](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplot).

##Pandas

Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language. We will see a quick introduction of how can we load, analyze and manipulate a real world dataset using `pandas`.

The primary data structures in *pandas* are implemented as two classes:

  * **`DataFrame`**, which is a 2-dimensional data structure that can store data of different types (including characters, integers, floating point values, categorical data and more) in columns. It is similar to a spreadsheet, a SQL table.

  * **`Series`**, which is a single column. A `DataFrame` contains one or more `Series` and a name for each `Series`.

We will only talk about `DataFrame` in this tutorial.

In [ ]:
import pandas as pd

We will load a sample dataset provided in Google Colab, called as  **California Housing Dataset**.



In [ ]:
california_housing_dataframe = pd.read_csv("/content/drive/MyDrive/Computer Vision/california_housing_train.csv")
# Reading a csv file and loading it as a dataframe

In [ ]:
california_housing_dataframe.head() # head() gives us the first 5 rows of the DataFrame.

In [ ]:
type(california_housing_dataframe) # Checking the type of california_housing_dataframe. Surpise : it is DataFrame

To select a single column, use square brackets `[]` with the column name of the column of interest.

In [ ]:
# selecting a single column named 'housing_median_age'
housing_median_age = california_housing_dataframe["housing_median_age"]
housing_median_age.head()

In [ ]:
type(housing_median_age) # Bonus question

If we want to select more than one column use a list of column names within the selection brackets `[]`.

In [ ]:
# selecting two columns namely : 'total_rooms' and 'total_bedrooms'
total_rooms_bed_rooms = california_housing_dataframe[["total_rooms", "total_bedrooms"]]
total_rooms_bed_rooms.head()

In [ ]:
total_rooms_bed_rooms.shape # The shape is arranged as (#rows, #columns)

How do I filter specific rows from a `DataFrame` ?

In [ ]:
california_housing_dataframe["total_rooms"] > 2000

In [ ]:
housing_median_age_greater_than_10 = california_housing_dataframe[california_housing_dataframe["total_rooms"] > 2000]
print(housing_median_age_greater_than_10.shape) # Note the change in the shape

If we require a subset, filtering both rows and columns then just using the selection brackets `[]` is not sufficient anymore.

We then, require `loc/iloc` operators in front of the selection brackets `[]`.

In [ ]:
print(california_housing_dataframe.iloc[1, 4])

When using `loc/iloc`, the part before the comma is the rows, and the part after the comma is the columns we desire to select.

In [ ]:
print(california_housing_dataframe.iloc[11:15, 4]) # Using slicing for selecting rows from 11 till 14

In [ ]:
print(california_housing_dataframe.loc[:, "total_rooms"])
# Assignment 2 : Difference between loc vs iloc

How to calculate summary statistics ?

In [ ]:
print(california_housing_dataframe["housing_median_age"].mean())
print(california_housing_dataframe[["total_rooms", "total_bedrooms"]].median())

The `describe()` method provides a quick overview of the numerical data in a DataFrame.
Note the columns with textual data are by default not taken into account by the `describe()` method.

In [ ]:
california_housing_dataframe[["total_rooms", "total_bedrooms"]].describe()

We can plot graphs for better visualization.

In [ ]:
california_housing_dataframe.hist('housing_median_age')
# Assignment 3 : What does the graph signify ?

You can have a further reading on `pandas` and how to get started in the officail [documentation](https://pandas.pydata.org/docs/getting_started/index.html#getting-started).

For more Colab operations follow this [tutorial](https://web.eecs.umich.edu/~justincj/teaching/eecs498/FA2020/colab.html).

##Seaborn

Seaborn is a Python data visualization library built on top of Matplotlib. It provides a high-level interface for creating attractive and informative statistical graphics. Seaborn is designed to work seamlessly with Pandas DataFrames and arrays, making it easy to visualize data from various data sources.


It complements Matplotlib and serves as a powerful tool for data visualization, especially for tasks involving statistical analysis and exploratory data analysis (EDA). Seaborn enhances the data visualization capabilities of Matplotlib and enables creation of more insightful and visually appealing plots with ease."

In [ ]:
sns.get_dataset_names()

In [ ]:
# Import the Seaborn library
import seaborn as sns

# Load the 'penguins' dataset from the Seaborn library
penguins = pd.read_csv('/content/drive/MyDrive/Computer Vision/penguins.csv')

penguins.head()

In [ ]:
# Create a scatter plot using Seaborn's scatterplot function
# Displaying 'bill_length_mm' on the x-axis and 'body_mass_g' on the y-axis
# The 'hue' parameter colors the points based on the 'species' column, showing
# different species with different colors. It is the grouping variable that will
# produce points with different colors
sns.scatterplot(data=penguins, x='bill_length_mm', y='body_mass_g', hue='species')

# Set the title of the plot
plt.title('Scatter Plot: Bill Length vs. Body Mass')

# Display the plot
plt.show()

In [ ]:
# A pair plot creates scatter plots for all numeric variables against each other.
# The 'hue' parameter is used to color the data points based on the 'species' column
sns.pairplot(penguins, hue="species", height=2)